FROM python:3.8-buster

COPY api api
COPY tensorflow_taxifare_deep tensorflow_taxifare_deep
COPY my_model.h5 my_model.h5
COPY my_pipeline.joblib my_pipeline.joblib
COPY requirements_m1.txt requirements_m1.txt

RUN pip install --upgrade pip
RUN pip install -r requirements_m1.txt

CMD uvicorn api.app:app --host 0.0.0.0 --port $PORT
